## Student ID: 2103654
## Assignment 2: matrix game
Compute all possible game matrix outcomes for n=3.

In [33]:
import numpy as np

def det(matrix):
    return np.linalg.det(matrix)

def generate_matrices():
    matrices = []
    
    #there are a total of 2**9 matrices that can have entries consisting of 0s and 1s
    for i in range(2**9):
        binary_representation = bin(i)[2:].zfill(9)  # Get binary representation with leading zeros
        
        # convert the binary representation into a 3x3 matrix
        matrix = np.array(list(map(int, binary_representation))).reshape(3, 3) #have to change string into integer

        # only want matrices with 4 or 5 ones, the rest zeros
        if np.sum(matrix) == 5 or np.sum(matrix) == 4:
            matrices.append(matrix)

    return matrices

def main():
    matrices = generate_matrices()

    for matrix in matrices:
        determinant = det(matrix)
        print(matrix)
        print("Determinant:", determinant)
        print("------------")

main()

[[0 0 0]
 [0 0 1]
 [1 1 1]]
Determinant: 0.0
------------
[[0 0 0]
 [0 1 0]
 [1 1 1]]
Determinant: 0.0
------------
[[0 0 0]
 [0 1 1]
 [0 1 1]]
Determinant: 0.0
------------
[[0 0 0]
 [0 1 1]
 [1 0 1]]
Determinant: 0.0
------------
[[0 0 0]
 [0 1 1]
 [1 1 0]]
Determinant: 0.0
------------
[[0 0 0]
 [0 1 1]
 [1 1 1]]
Determinant: 0.0
------------
[[0 0 0]
 [1 0 0]
 [1 1 1]]
Determinant: 0.0
------------
[[0 0 0]
 [1 0 1]
 [0 1 1]]
Determinant: 0.0
------------
[[0 0 0]
 [1 0 1]
 [1 0 1]]
Determinant: 0.0
------------
[[0 0 0]
 [1 0 1]
 [1 1 0]]
Determinant: 0.0
------------
[[0 0 0]
 [1 0 1]
 [1 1 1]]
Determinant: 0.0
------------
[[0 0 0]
 [1 1 0]
 [0 1 1]]
Determinant: 0.0
------------
[[0 0 0]
 [1 1 0]
 [1 0 1]]
Determinant: 0.0
------------
[[0 0 0]
 [1 1 0]
 [1 1 0]]
Determinant: 0.0
------------
[[0 0 0]
 [1 1 0]
 [1 1 1]]
Determinant: 0.0
------------
[[0 0 0]
 [1 1 1]
 [0 0 1]]
Determinant: 0.0
------------
[[0 0 0]
 [1 1 1]
 [0 1 0]]
Determinant: 0.0
------------
[[0 0 0]
 [1 1

In [53]:
#experimenting with fixing certain entries

#here fix centre entry=0

def generate_matrices():
    matrices = []
    for i in range(2**7):  # Since we fix some entries, there are only 2^7 possibilities left
        binary_representation = bin(i)[2:].zfill(7)  # Get binary representation with leading zeros
        matrix = np.zeros((3, 3), dtype=int)

        # Fix the specified entries
        matrix[1, 1] = 0  # '0' in the second row middle entry
        
        # Fill the rest of the matrix based on the binary representation
        matrix[0, 0] = int(binary_representation[0])
        matrix[0, 2] = int(binary_representation[1])
        matrix[1, 2] = int(binary_representation[2])
        matrix[2, 0] = int(binary_representation[3])
        matrix[2, 2] = int(binary_representation[4])
        matrix[1, 0] = int(binary_representation[5])
        matrix[0, 1] = int(binary_representation[6])

        # Add the 2x2 identity matrix in the bottom left corner
        matrix[1:, :2] = np.eye(2)

        # Check if the matrix satisfies the condition
        if np.sum(matrix) == 5 or np.sum(matrix) == 4:
            matrices.append(matrix)

    return matrices

def main(m):
    matrices = generate_matrices()
    
    numtoprint=m
    printed=0
    
    for matrix in matrices:
        determinant = det(matrix)
        print(matrix)
        print("Determinant:", determinant)
        print("------------")
        
        printed+=1
        if printed==numtoprint:
            break



m = int(input("Enter how many examples to print: "))
print("You entered:", m)

main(m)
print('Just printing the first,', m, 'examples, we can having a 0 in the centre does not ensure our determinant is always 0.')

Enter how many examples to print:  10


You entered: 10
[[0 1 0]
 [1 0 0]
 [0 1 1]]
Determinant: -1.0
------------
[[0 1 0]
 [1 0 0]
 [0 1 1]]
Determinant: -1.0
------------
[[0 1 0]
 [1 0 0]
 [0 1 1]]
Determinant: -1.0
------------
[[0 1 0]
 [1 0 0]
 [0 1 1]]
Determinant: -1.0
------------
[[0 1 0]
 [1 0 1]
 [0 1 0]]
Determinant: 0.0
------------
[[0 1 0]
 [1 0 1]
 [0 1 0]]
Determinant: 0.0
------------
[[0 0 0]
 [1 0 1]
 [0 1 1]]
Determinant: 0.0
------------
[[0 1 0]
 [1 0 1]
 [0 1 1]]
Determinant: -1.0
------------
[[0 0 0]
 [1 0 1]
 [0 1 1]]
Determinant: 0.0
------------
[[0 1 0]
 [1 0 1]
 [0 1 1]]
Determinant: -1.0
------------
Just printing the first, 10 examples, we can having a 0 in the centre does not ensure our determinant is always 0.


In [49]:
#check our copycat strategy for n=4

#copycat function
def copycat(n):
    List = []
    
    #2*num since each entry can either take a 0 or 1
    for i in range(2 ** (2 * n)):
    # Using binary numbers to fill in matrix
        binary = bin(i)[2:].zfill(2 * n)
        
        # two columns to copycat
        leftcol = np.array(list(map(int, binary))).reshape(n, int(n / 2)) 
        empty = np.zeros((n, n))
        
        # Duplicate and invert the columns
        empty[:, ::2] = leftcol  # Copy original columns to even columns
        empty[:, 1::2] = 1 - leftcol  # Invert for the copycat, set to odd columns
        
        List.append(empty)

    return List

# Listing valid matrices with the Determinant
def ccPrint(n,m):
    numtoprint=m
    printed=0
    
    matrix = copycat(n)
    for mat in matrix:
        deter = det(mat)
        print(mat)
        print("Determinant:", deter)
        print("------------")
        
        printed+=1
        if printed==numtoprint:
            break
    
toprint = int(input("Enter how many examples to print: "))
print("You entered:", toprint)

ccPrint(4, toprint)
print('Just printing the first,', toprint, 'examples, we can see our copycat method always gives a determinant of 0 for n=4!')

Enter how many examples to print:  5


You entered: 5
[[0. 1. 0. 1.]
 [0. 1. 0. 1.]
 [0. 1. 0. 1.]
 [0. 1. 0. 1.]]
Determinant: 0.0
------------
[[0. 1. 0. 1.]
 [0. 1. 0. 1.]
 [0. 1. 0. 1.]
 [0. 1. 1. 0.]]
Determinant: 0.0
------------
[[0. 1. 0. 1.]
 [0. 1. 0. 1.]
 [0. 1. 0. 1.]
 [1. 0. 0. 1.]]
Determinant: 0.0
------------
[[0. 1. 0. 1.]
 [0. 1. 0. 1.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]
Determinant: 0.0
------------
[[0. 1. 0. 1.]
 [0. 1. 0. 1.]
 [0. 1. 1. 0.]
 [0. 1. 0. 1.]]
Determinant: 0.0
------------
Just printing the first, 5 examples, we can see our copycat method always gives a determinant of 0 for n=4!


In [40]:
#Review section

#Trying a small example using copycat strategy idea

mat1=[[0,1,1],
     [1,0,0]]

mat2=[[1,0],
      [0,1],
      [1,0]]

print('Determinant is', det(np.matmul(mat1,mat2)))
print('Copycat does not easily transfer over.')

Determinant is -1.0
Copycat does not easily transfer over.
